version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(levelname)s:\t%(asctime)s %(name)s|%(filename)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    maxBytes: 10485760 # 10mb
    backupCount: 20 # 20 days
    encoding: utf8
    filename: /Users/cam/Code/bypass/_data/logs/main.log

root:
  level: DEBUG
  handlers: [console,file]